### ISSUE TITLE
`KinesisDataFetcher#stopWithError` should log exception so that the root cause can be observed

### ISSUE THREAD

**Issue by bobtiernay-okta** [awslabs/amazon-kinesis-connector-flink#22]
Currently we are experiencing an issues where the `ShardConsumer#run` method is throwing an exception, calling `KinesisDataFetcher#stopWithError`.  The method then internally calls `shutdownFetcher`. However, there is nothing in this sequence of actions that logs which exception was thrown and thus it becomes impossible to diagnose the root cause:

![image](https://user-images.githubusercontent.com/25536705/115059965-44794700-9eb5-11eb-97e3-f768a2843383.png)

In such a situation, we should more early log since in this particular case, the application is deadlocked in `awaitTermination` and future logging never materializes. The `ShardConsumer#run` `catch (Throwable t)` block is one candidate, and `KinesisDataFetcher#stopWithError` or `KinesisDataFetcher#shutdownFetcher` are others.

**Comment by dannycranmer** [comment]
Addressed in https://github.com/awslabs/amazon-kinesis-connector-flink/pull/25. Will be included in `v2.0.3`
