### ISSUE TITLE
An exception in `KinesisDataFetcher#shutdownFetcher` may fail to shutdown `shardConsumersExecutor` leading to job hanging

### ISSUE THREAD

**Issue by bobtiernay-okta** [awslabs/amazon-kinesis-connector-flink#23]
The [following code](https://github.com/awslabs/amazon-kinesis-connector-flink/blob/38ad8b479ba90307b539ab889034a7a39358a803/src/main/java/software/amazon/kinesis/connectors/flink/internals/KinesisDataFetcher.java#L738-L764):
```java
public void shutdownFetcher() {
	if (LOG.isInfoEnabled()) {
		LOG.info("Starting shutdown of shard consumer threads and AWS SDK resources of subtask {} ...",
				indexOfThisConsumerSubtask);
	}

	running = false;

	StreamConsumerRegistrarUtil.deregisterStreamConsumers(configProps, streams);

	recordPublisherFactory.close();

	shardConsumersExecutor.shutdownNow();

	if (mainThread != null) {
		mainThread.interrupt(); // the main thread may be sleeping for the discovery interval
	}

	if (watermarkTracker != null) {
		watermarkTracker.close();
	}
	this.recordEmitter.stop();

	if (LOG.isInfoEnabled()) {
		LOG.info("Shutting down the shard consumer threads of subtask {} ...", indexOfThisConsumerSubtask);
	}
}
```

May lead to a stuck job if after settings `running = false`  any of the following throws an exception:

- `StreamConsumerRegistrarUtil#deregisterStreamConsumers` 
- `recordPublisherFactory.close()`

When this happens, the `mainThread` will hang in `#runFetcher`'s call to `#awaitTermination` forever since `shardConsumersExecutor.shutdownNow()` is never called. 

Note that this was extremely hard to debug due to lack of logging. Highly suggest a more fortified `shutdownFetcher` with error handling and best effort cleanup of the methods that can throw.

**Comment by dannycranmer** [comment]
Addressed in https://github.com/awslabs/amazon-kinesis-connector-flink/pull/24 and will be included in `2.0.3`

**Comment by bobtiernay-okta** [comment]
@dannycranmer Thanks a lot! Any ETA on when this might be released?

**Comment by dannycranmer** [comment]
@bobtiernay-okta it is currently running through our test suite. Once this is green I will finalise and push out
