### ISSUE TITLE
`FlinkKinesisConsumer` metric groups and publication should be externally configurable

### ISSUE THREAD

**Issue by bobtiernay-okta** [awslabs/amazon-kinesis-connector-flink#29]
# Problem

Today, there is no way to configure the metrics produced by `FlinkKinesisConsumer` and its subcomponents. This can lead to large metric related costs for streams with a large number of shards in environment such as Amazon Kinesis Data Analytics for Apache Flink where downstream where platform control is limited. In some scenarios, stream level metrics are sufficient for observability.  Having the ability to select the metrics, along with their granularity (i.e. selection of sub metric groups) give greater control to users and relieve them from having to fork the code to achieve such ends.

# Proposal

Expose the ability to effect the metric group setup in `KinesisDataFetcher#runFetcher`. 

Specifically, in this block of code:
```java
        shardDeserializationSchema.open(() -> consumerMetricGroup
		        .addGroup("subtaskId", String.valueOf(indexOfThisConsumerSubtask))
		        .addGroup("shardId", streamShardHandle.getShard().getShardId())
		        .addGroup("user"));
```

It should be possible to include or exclude any subset of `subtaskId`, `shardId`, `user`, including the empty set.

Similarly, in this code:
```java
        shardConsumersExecutor.submit(
		        createShardConsumer(
				        seededStateIndex,
				        streamShardHandle,
				        subscribedShardsState.get(seededStateIndex).getLastProcessedSequenceNum(),
				        registerShardMetricGroup(
						        consumerMetricGroup, subscribedShardsState.get(seededStateIndex)),
				        shardDeserializationSchema));

        ...

        private MetricGroup registerShardMetricGroup(final MetricGroup metricGroup, final KinesisStreamShardState shardState) {
        return metricGroup
		        .addGroup(
				        KinesisConsumerMetricConstants.STREAM_METRICS_GROUP,
				        shardState.getStreamShardHandle().getStreamName())
		        .addGroup(
				        KinesisConsumerMetricConstants.SHARD_METRICS_GROUP,
				        shardState.getStreamShardHandle().getShard().getShardId());
        }
```

It should be possible to  include or exclude any subset of `streamName`, `shardId`,  including the empty set, as well as configure which of the following to publish in `ShardConsumerMetricsReporter` or `PollingRecordPublisherMetricsReporter`s:

```java
	public static final String MILLIS_BEHIND_LATEST_GAUGE = "millisBehindLatest";
	public static final String SLEEP_TIME_MILLIS = "sleepTimeMillis";
	public static final String MAX_RECORDS_PER_FETCH = "maxNumberOfRecordsPerFetch";
	public static final String NUM_AGGREGATED_RECORDS_PER_FETCH = "numberOfAggregatedRecordsPerFetch";
	public static final String NUM_DEAGGREGATED_RECORDS_PER_FETCH = "numberOfDeaggregatedRecordsPerFetch";
	public static final String AVG_RECORD_SIZE_BYTES = "averageRecordSizeBytes";
	public static final String RUNTIME_LOOP_NANOS = "runLoopTimeNanos";
	public static final String LOOP_FREQUENCY_HZ = "loopFrequencyHz";
	public static final String BYTES_PER_READ = "bytesRequestedPerFetch";
```

**Comment by dannycranmer** [comment]
@bobtiernay-okta we are not planning on adding new features to this repository. I propose you open a Jira in the apache project and we can take it from there. Please add the Jira reference here if you do not mind
