### ISSUE TITLE
Problems encountered when using aws connector to replace flink connector to connect kinesis stream in flink

### ISSUE THREAD

**Issue by SOD-DOB** [awslabs/amazon-kinesis-connector-flink#34]
Before I used the flink connector to connect the kinesis stream, there would always be such a problem 
![image](https://user-images.githubusercontent.com/47728686/121477981-1454ad00-c9fb-11eb-8966-88d88031bb8f.png)

The following is my previous pom 
`        <dependency>`
`            <groupId>org.apache.flink</groupId>`
`            <artifactId>flink-connector-kinesis_2.12</artifactId>`
`            <version>1.11.3</version>`
`        </dependency>`

When I replace with aws connector 
`        <dependency>`
`            <groupId>software.amazon.kinesis</groupId>`
`            <artifactId>amazon-kinesis-connector-flink</artifactId>`
`            <version>2.0.3</version>`
`        </dependency>` 

The following error occurred, but I could not find the related package exception
![image](https://user-images.githubusercontent.com/47728686/121478416-93e27c00-c9fb-11eb-81b4-1eceff4a928b.png)

Can you help me answer it?

**Comment by dannycranmer** [comment]
Are you getting this error with a clean Flink job, with no state? Or are you trying to restore from an old checkpoint or savepoint?

**Comment by dannycranmer** [comment]
Closing due to staleness, please reopen if needed
