### ISSUE TITLE
Publish the latest version to Maven central

### ISSUE THREAD

**Issue by vitaliislobodianyk-okta** [awslabs/amazon-kinesis-connector-flink#58]
The latest version of the connector for Flink 1.11 available in [Maven central repository](https://mvnrepository.com/artifact/software.amazon.kinesis/amazon-kinesis-connector-flink) is `2.3.0`, while the README mentions `2.3.1`.

**Comment by dannycranmer** [comment]
Thanks for reporting this @vitaliislobodianyk-okta. We will promote the build to maven central soon.

**Comment by dannycranmer** [comment]
Sorry for the delay, all versions have been deployed to Maven central. It may take a few hours for the jars to show up.
