### ISSUE TITLE
(Python) Unable to convert kinesis table into datastream

### ISSUE THREAD

**Issue by mattfysh** [awslabs/amazon-kinesis-connector-flink#64]
1. Running v1.16.0
2. Using the session mode docker cluster as defined here: https://nightlies.apache.org/flink/flink-docs-release-1.16/docs/deployment/resource-providers/standalone/docker/#session-mode-1
3. Using the custom dockerfile as defined here: https://nightlies.apache.org/flink/flink-docs-release-1.16/docs/deployment/resource-providers/standalone/docker/#using-flink-python-on-docker
4. Updated version of python to be v3.9.15
5. Downloaded the flink jars from https://mvnrepository.com/artifact/org.apache.flink/flink-connector-kinesis/1.16.0 (and SQL equivalent)
6. Ssh'ing into the job manager and running `./bin/flink run --python /opt/test/my_app.py`

```py
from pyflink.datastream import StreamExecutionEnvironment
from pyflink.table import StreamTableEnvironment
from pyflink.common.typeinfo import Types

env = StreamExecutionEnvironment.get_execution_environment()
t_env = StreamTableEnvironment.create(stream_execution_environment=env)
t_env.get_config().set('pipeline.jars', 'file:///opt/test/flink-sql-connector-kinesis-1.16.0.jar')

# define streaming kinesis source
t_env.execute_sql("""
  CREATE TABLE my_stream (
    id STRING
  )
  WITH (
      'connector' = 'kinesis',
      'stream' = 'my_stream',
      'aws.region' = 'ap-southeast-2',
      'scan.stream.initpos' = 'LATEST',
      'format' = 'json'
    )
""")

# convert table to datastream
ds = t_env.to_append_stream(
  t_env.from_path('my_stream'),
  Types.ROW([Types.STRING()])
)

ds.print()
env.execute()
```

This produces the error:

```
Caused by: java.lang.ClassNotFoundException: org.apache.flink.streaming.api.operators.python.process.ExternalPythonProcessOperator
```

**Comment by mattfysh** [comment]
Similarly unable to get the datastream connector working due to another class loading issue:

```py
env = StreamExecutionEnvironment.get_execution_environment()
env.add_jars('file:///opt/test/flink-connector-kinesis-1.16.0.jar')

kinesis = env.add_source(
  FlinkKinesisConsumer('my_stream', SimpleStringSchema(), {
    'aws.region': 'ap-southeast-2',
    'aws.credentials.provider': 'ENV_VAR',
    'flink.stream.initpos': 'LATEST'
  })
)
kinesis.print()
env.execute()
```

```
Caused by: java.lang.ClassNotFoundException: org.apache.commons.logging.LogFactory
```

**Comment by dannycranmer** [comment]
This issue is not related to this connector, from the looks of things you might need to use the SQL (uber) jar. Btw the SQL and non-SQL jar are identical besides the fact the SQL is an uber jar build. They do not target different APIs. both jars can be used for DataStream/Table/SQL API. The SQL tag means it is intended to be used with the SQL client.

**Comment by mattfysh** [comment]
I tried both connectors, in my first comment I am using the SQL connector and in the second I am using the thin connector.

When I list the contents of both thin and uber JARs, the two classes mentioned in the `ClassNotFoundException` errors are not found in either.

I downloaded the JARs from mvnrepository.com as instructed in the AWS documentation.

**Comment by dannycranmer** [comment]
> When I list the contents of both thin and uber JARs, the two classes mentioned in the ClassNotFoundException errors are not found in either.

It is not expected for these classes to be bundled into the connector. Unfortunately I am not very experienced with Python or PyFlink, you would be better engaging AWS support or asking on the Apache Flink slack channel.
